DROP DATABASE IF EXISTS DBALUNO;
CREATE DATABASE DBALUNO;
USE DBALUNO;

CREATE TABLE ALUNO (
	IDALUNO INT NOT NULL AUTO_INCREMENT
	, NOME VARCHAR(20) NOT NULL
	, SEXO CHAR(1)
	, IDADE INT
	, CIDADE VARCHAR(20)
    , PRIMARY KEY (IDALUNO)
);

INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('EDENILSON', 17, 'M','CURITIBA');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('CESAR', 21, 'M', 'SAO JOSE');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('CARLOS', 19, 'M', 'CAXIAS');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('DIEGO', 19, 'M', 'BLUMENAU');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('EDUARDO', 20, 'M', NULL);
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('GABRIEL', 19, 'M', 'TUBARAO');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('JOAO', 18, 'M', 'SAO JOSE');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('LEONARDO', 19, 'M', NULL);
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('LUCAS', 20, 'M', 'BLUMENAU');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('LAURA', 19, 'F', 'PALHOÇA');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('RENATA', 21, 'F', 'TRENTO');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('MARIA', 22, 'F', 'BLUMENAU');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('MELISSA', 19, 'F', 'SAO JOSE');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('CARLOS', 22, 'M', 'TUBARAO');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('MONTEIRO', 19, 'M', 'PALHOCA');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('MAISA', 19, 'F', NULL);
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('AMANDA', 20, 'F', NULL);
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('JOANA', 19, 'F', NULL);
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('ALICE', 21, 'F', 'SAO JOSE');
INSERT INTO ALUNO (NOME, IDADE, SEXO, CIDADE)VALUES('JORGE', 18, 'M', 'GRAMADO');

SELECT * FROM ALUNO WHERE SEXO = 'M';
SELECT * FROM ALUNO WHERE IDADE = 19;

SELECT * FROM ALUNO WHERE NOME LIKE 'D%';

SELECT * FROM ALUNO WHERE (IDADE >= 20 AND IDADE <= 22);
SELECT * FROM ALUNO WHERE CIDADE IS NULL;
SELECT * FROM ALUNO WHERE CIDADE = 'Blumenau';

SELECT * FROM ALUNO WHERE IDADE <> 18;
SELECT * FROM ALUNO WHERE NOME LIKE '%ri%';

SELECT * FROM ALUNO WHERE (CIDADE = 'SÃO JOSÉ' AND SEXO = 'M' AND IDADE < 20);
SELECT * FROM ALUNO WHERE (IDADE >= 17 AND SEXO = 'M') OR (IDADE >= 20 AND SEXO = 'F') ;
SELECT * FROM ALUNO WHERE (NOME LIKE '%A%' or NOME LIKE '%R%');

SELECT NOME, IDADE FROM ALUNO WHERE SEXO = 'F';
SELECT IDALUNO, NOME FROM ALUNO WHERE CIDADE = 'BLUMENAU';
SELECT NOME, CIDADE FROM ALUNO WHERE IDADE < 18;
SELECT NOME, CIDADE FROM ALUNO WHERE (IDADE >= 15 AND IDADE <= 18 AND CIDADE <> 'PALHOÇA');

SELECT CIDADE FROM ALUNO WHERE CIDADE IS NOT NULL;
SELECT NOME FROM ALUNO WHERE (CIDADE = 'SÃO JOSÉ' AND IDADE = 17) or (CIDADE = 'PALHOÇA' AND IDADE = 18) ;
SELECT NOME FROM ALUNO WHERE (IDADE >= 18 AND IDADE <= 25 AND CIDADE = 'TUBARÃO' AND SEXO = 'M');

SELECT NOME, IDADE FROM ALUNO ORDER BY IDADE;
SELECT IDALUNO, NOME FROM ALUNO ORDER BY NOME DESC;

SELECT * FROM ALUNO order by IDADE DESC;
SELECT * FROM ALUNO order by NOME ASC;

SELECT * FROM ALUNO order by SEXO;
SELECT * FROM ALUNO order by NOME;
